# Generated by Django 4.1.7 on 2023-03-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'column',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('idcol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jskanbanproject.column')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
